version: 2.1

####### YAML ANCHORS #######

mongodb-container: &mongodb-container
  image: circleci/mongo:5.0.3

zookeeper-container: &zookeeper-container
  image: confluentinc/cp-zookeeper:6.2.0
  environment:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000

kafka-container: &kafka-container
  image: confluentinc/cp-kafka:6.2.0
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

####### CIRCLECI JOBS #######

jobs:
  speech-processor:
    resource_class: small
    docker:
      - image: python:3.10-slim
      - *mongodb-container
      - *kafka-container
      - *zookeeper-container
    environment:
      SPEECH_ENV: 'test'
      MONGO_DB: speech_processor_test
      MONGO_URL: 'localhost:27017'
      KAFKA_URL: 'localhost:9092'
      KAFKA_RESOURCE_TOPIC: speech_processor_resource_test
    steps:
      - checkout
      - run:
          name: "Install system dependencies"
          command: apt-get update && apt-get install --no-install-recommends -y git ffmpeg
      - run:
          name: "Install Python Development requirements"
          command: pip3 install --no-cache-dir -r requirements-dev.txt
      - run:
          name: "Run Tests with coverage"
          command: |
            python3 -m coverage run -m pytest tests --tb=native --verbosity=1
            python3 -m coverage report
            coveralls

####### CIRCLECI WORKFLOWS #######

workflows:
  speech-processor-workflow:
    jobs:
      - speech-processor
