version: 2.1

####### YAML ANCHORS #######

mongodb-container: &mongodb-container
  image: circleci/mongo:4.4.5

####### CIRCLECI JOBS #######

jobs:
  speech-processor:
    resource_class: small
    docker:
      - image: cimg/python:3.10.0
      - *mongodb-container
    environment:
      GOOGLE_LOCAL: '1'
      SPEECH_ENV: 'test'
      MONGO_DB: speech_processor_test
    steps:
      - checkout
      - run:
          name: "Install Python Development requirements"
          command: pip3 install --no-cache-dir -r requirements-dev.txt
      - run:
          name: "Install ffmpeg"
          command: sudo apt-get -y update && sudo apt-get install -y ffmpeg
      - run:
          name: "Run Tests"
          command: python3 -u -m pytest tests --tb=native -rP

####### CIRCLECI WORKFLOWS #######

workflows:
  speech-processor-workflow:
    jobs:
      - hold:
          type: approval
      - speech-processor:
          requires:
            - hold
